server:
  port: 8080
spring:
  application:
    name: inventory-service
  profiles:
    active: local
  datasource:
    url: jdbc:mysql://localhost:3306/inventory
    username: root
    password: Password4$
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true